version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /client/platform/android
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /client/platform/kmp
    schedule:
      interval: weekly
