#!/usr/bin/env python3
"""Validate the versioned host IDL and generate stable cross-platform contracts."""

import argparse
import json
import os
import re
from pathlib import Path

from .compiler import CompileError


IDENTIFIER = re.compile(r"[a-z][a-z0-9]*(?:[._][A-Za-z][A-Za-z0-9]*)+")
TYPES = {"bool", "int", "string"}
DEFAULT_IDL = Path(__file__).resolve().parents[3] / "spec" / "host_idl.json"


def _require(condition, message):
    if not condition:
        raise CompileError(message)


def load(path):
    try:
        source = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise CompileError("cannot read host IDL: %s" % error)
    _require(source.get("schemaVersion") == 1, "unsupported host IDL schema")
    for section in ("capabilities", "components"):
        entries = source.get(section)
        _require(isinstance(entries, list), "%s must be a list" % section)
        ids = [entry.get("id") for entry in entries if isinstance(entry, dict)]
        _require(len(ids) == len(entries), "%s entries must be objects" % section)
        _require(ids == sorted(ids), "%s must be sorted by id" % section)
        _require(len(ids) == len(set(ids)), "%s ids must be unique" % section)
        for entry in entries:
            _require(IDENTIFIER.fullmatch(entry["id"]) is not None, "invalid IDL id: %r" % entry["id"])
            _require(isinstance(entry.get("version"), int) and entry["version"] > 0,
                     "%s version must be positive" % entry["id"])
    for capability in source["capabilities"]:
        _require(isinstance(capability.get("async"), bool),
                 "%s async must be boolean" % capability["id"])
        operations = capability.get("operations")
        _require(isinstance(operations, dict) and operations,
                 "%s requires operations" % capability["id"])
        for name, operation in operations.items():
            _require(re.fullmatch(r"[a-z][A-Za-z0-9]*", name) is not None,
                     "invalid operation: %s.%s" % (capability["id"], name))
            _require(isinstance(operation, dict), "operation must be an object")
            _require(
                isinstance(operation.get("args"), list)
                and all(value in TYPES for value in operation["args"])
                and operation.get("result") in TYPES,
                "invalid operation types: %s.%s" % (capability["id"], name),
            )
    for component in source["components"]:
        for field in ("props", "events", "commands"):
            _require(isinstance(component.get(field), dict),
                     "%s.%s must be an object" % (component["id"], field))
        _require(all(value in TYPES for value in component["props"].values()),
                 "%s has invalid prop types" % component["id"])
        _require(all(value in TYPES for value in component["events"].values()),
                 "%s has invalid event types" % component["id"])
        _require(all(isinstance(value, list) and all(item in TYPES for item in value)
                     for value in component["commands"].values()),
                 "%s has invalid command types" % component["id"])
    return source


def _symbol(value):
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def generate(source):
    canonical = json.dumps(source, indent=2, sort_keys=True) + "\n"
    kotlin = [
        "// Generated by pvm_server.host_idl; do not edit.",
        "package com.protectedvm.generated",
        "",
        "object PvmHostIds {",
    ]
    swift = [
        "// Generated by pvm_server.host_idl; do not edit.",
        "public enum PVMHostIds {",
    ]
    arkts = [
        "// Generated by pvm_server.host_idl; do not edit.",
        "export class PvmHostIds {",
    ]
    cpp = [
        "// Generated by pvm_server.host_idl; do not edit.",
        "#pragma once",
        "",
        "namespace pvm::generated {",
    ]
    for section, prefix in (("capabilities", "CAPABILITY"), ("components", "COMPONENT")):
        for entry in source[section]:
            name = "%s_%s" % (prefix, _symbol(entry["id"]))
            value = entry["id"]
            version = entry["version"]
            symbol = "".join(part.title() for part in name.lower().split("_"))
            kotlin.append('    const val %s = "%s"' % (name, value))
            kotlin.append("    const val %s_VERSION = %d" % (name, version))
            swift.append('    public static let %s = "%s"' % (name.lower(), value))
            swift.append("    public static let %s_version = %d" % (name.lower(), version))
            arkts.append("  static readonly %s: string = '%s'" % (name, value))
            arkts.append("  static readonly %s_VERSION: number = %d" % (name, version))
            cpp.append('inline constexpr const char* k%s = "%s";' % (symbol, value))
            cpp.append("inline constexpr unsigned k%sVersion = %d;" % (symbol, version))
    kotlin += ["}", ""]
    swift += ["}", ""]
    arkts += ["}", ""]
    cpp += ["}  // namespace pvm::generated", ""]
    mock = {
        capability["id"]: {
            operation: json.dumps(
                {"error": "mock response is not configured", "ok": False},
                separators=(",", ":"),
                sort_keys=True,
            )
            for operation in capability["operations"]
        }
        for capability in source["capabilities"]
    }
    return {
        "host-idl.canonical.json": canonical,
        "mock/default-responses.json": json.dumps(mock, indent=2, sort_keys=True) + "\n",
        "kotlin/PvmHostIds.kt": "\n".join(kotlin),
        "swift/PVMHostIds.swift": "\n".join(swift),
        "arkts/PvmHostIds.ets": "\n".join(arkts),
        "cpp/pvm_host_ids.hpp": "\n".join(cpp),
    }


def write_outputs(source, output):
    output = Path(output)
    for relative, content in generate(source).items():
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = destination.with_suffix(destination.suffix + ".tmp")
        temporary.write_text(content, encoding="utf-8")
        os.replace(str(temporary), str(destination))


def check_outputs(source, output):
    mismatches = [
        relative
        for relative, content in generate(source).items()
        if not (Path(output) / relative).is_file()
        or (Path(output) / relative).read_text(encoding="utf-8") != content
    ]
    if mismatches:
        raise CompileError("generated host contracts are stale: " + ", ".join(mismatches))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--idl", default=DEFAULT_IDL, type=Path)
    parser.add_argument("--output", default="generated/host", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        source = load(args.idl)
        check_outputs(source, args.output) if args.check else write_outputs(source, args.output)
    except CompileError as error:
        parser.error(str(error))
    print(args.output)


if __name__ == "__main__":
    main()
